_target_: boltzgen.task.predict.predict_solublempnn.PredictSolubleMPNN
data:
  _target_: boltzgen.task.predict.data_from_generated.FromGeneratedDataModule
  cfg:
    _target_: boltzgen.task.predict.data_from_generated.DataConfig
    tokenizer:
      _target_: boltzgen.data.tokenize.tokenizer.Tokenizer
      atomize_modified_residues: false
    featurizer:
      _target_: boltzgen.data.feature.featurizer.Featurizer
    suffix: .cif
    suffix_metadata: .npz
    suffix_native: _native.cif
    moldir: null
    samples_per_target: 1000000000
    design: true
    backbone_only: true
    atom14: false
    max_seqs: 1
    inverse_fold: true
    batch_size: 1
    num_workers: 4
    pin_memory: true
    num_targets: 1000000000
    design_mask_override: null
  fail_if_no_designs: true
  design_dir: null
  output_dir: ${output}
writer:
  _target_: boltzgen.task.predict.writer.DesignWriter
  output_dir: ${output}
  res_atoms_only: false
  atom14: ${data.cfg.atom14}
  inverse_fold: ${data.cfg.inverse_fold}
  write_native: false
trainer:
  accelerator: gpu
  devices: 1
  precision: 32
name: inverse_fold_solublempnn
output: null
checkpoint: null
matmul_precision: null
sampling_temperature: 0.1
inverse_fold_restriction: []
